Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Identity_V2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Identity_V2.Controllers
{
    [Authorize]
    public class RolesController : Controller
    {
        private readonly RoleManager<AppRole> _roleManager;

        public RolesController(RoleManager<AppRole> roleManager)
        {

            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Login", "Account");
            }
            return View(_roleManager.Roles);

        }
        [HttpPost]
        public async Task<IActionResult> Create(AppRole model)
        {

            if (ModelState.IsValid)
            {

                var result = await _roleManager.CreateAsync(model);

                if (result.Succeeded)
                {

                    return RedirectToAction("Index");
                }

                foreach (var err in result.Errors)
                {
                    ModelState.AddModelError("", err.Description);
                }
            }
            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }


    }


}

Views/Shared/_Layout.cshtml
@if(TempData["message"] != null){

<div class="alert alert-warning">
    @TempData["message"]
</div>
}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Identity_V2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Identity_V2.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Identity_V2</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link btn btn-dark text-light mr-2" asp-area="" asp-controller="Home"
                                asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-dark text-light mr-2" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin")){
                        <li class="nav-item">
                            <a class="nav-link btn btn-dark text-light mr-2" asp-area="" asp-controller="Users"
                                asp-action="List">Kullanıcı Listesi</a>
                        </li>
                        <!-- <li class="nav-item">
                            <a class="nav-link btn btn-dark text-light mr-3" asp-area="" asp-controller="Account"
                                asp-action="Create">Kullanıcı Oluştur</a>
                        </li> -->
                        <li class="nav-item">
                            <a class="nav-link btn btn-dark text-light mr-2" asp-area="" asp-controller="Roles"
                                asp-action="Index">Roller</a>
                        </li>
                        }

                    </ul>
                    <ul class="navbar-nav ms-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark">Merhaba, @User.Identity.Name</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link btn btn-dark text-light" asp-controller="Account"
                                asp-action="Logout">Çıkış Yap</a>
                        </li>
                        }


                    </ul>
                </div>


            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Identity_V2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>